flight:
  host: "lakshay-process-flight-partner-api.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basePath: "/api/"
  
car:
  host: "lakshay-process-car-rental-partner-api.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basePath: "/api/"
  
hotel:
  host: "lakshay-process-hotel-partner-api.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basePath: "/api/"
  
application:
  clientID: "![b1YN++Dm/hXn6ddRii8KscY26oCI6twDcPnatiDrUgeIfP9ouIhZoK7iBTyHwAmR]"
  clientSecret: "![cM2hGJcnEWFsmxfqNt6Itx4vgspD/LeKDlH/r/Y04g1Ao9yWlidbFqm88ZBhl0IT]"
  
api:
  id: "17485444"